# Generated by Django 3.2.18 on 2023-04-14 08:17

import app_shops.models
import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=70, populate_from=app_shops.models.get_latin_name, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('icon', models.FileField(blank=True, null=True, upload_to='static/img/icons/departments/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='icon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='app_shops.catalog', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'catalog',
            },
        ),
    ]
